packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxtjs/color-mode': ^3.5.2
    '@unocss/eslint-config': ^66.3.2
    '@unocss/nuxt': ^66.3.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.4.0
    nuxt: ^3.17.5
    unocss: ^66.3.2
    unplugin: ^2.3.5
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.16.1
    eslint: ^9.30.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.10
  frontend:
    '@vueuse/core': ^13.4.0
    vue: ^3.5.17
  icons:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/simple-icons': ^1.2.40
    '@iconify-json/twemoji': ^1.2.2
  utils:
    '@nuxtjs/dayjs': ^1.4.1
    '@types/node': ^24.0.7
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.39.5
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
